language: rust

env:
  global:
    - secure: O0FEJxWkNfTCZlMqS17D/qG4k4henuwD/A2JVCvUTa0fuEz+wsMoE4s9RVB5aAXM6kU0dni/sJTUPG3JhZUcKaIjUe+nOxwSsllw2YKbqeGjpjOdZI9z21jSrS5N3V0cGhx/qOLgL6+R0LYGwR+jDlahrIAZ6UOX0N7UnJ6EdKQ=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
