language: rust
sudo: false

env:
  global:
    - secure: GWRw12HvGA7Wz9MmDd4WWUBJOUAUpmL/JWmXyl3B8xrJN8U60CcvXIL7AhOKRrqgl9q0AI6fEZVSzV4wzvJAUlbWjk1rDKOwAc2LixwhmfnlxZv+qS+P4usZKXgp4vGgkNoNcOG1UYDHkQtCP1POtoY7ULyf7NcEI+g6IID9clE=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
